import pandas as pd
configfile: "../config/config.yaml"
SAMPLES = pd.read_csv(config["sample_file"])['sample_id']

include: "rules/common.smk"
include: "rules/references.smk"
include: "rules/trim.smk"
include: "rules/deseq2.smk"
# Include custom rules defined in the config.
if "custom_rules" in config:
    for rule_file in config["custom_rules"]:
        include: rule_file

    
    
rule all:
    input:
        "../results/deseq2/dds.rds"